#!/usr/bin/env php
<?php
require_once __DIR__."/libs/autoload.php";
$Console = new Symfony\Component\Console\Application;

// COMMANDS
$Console->add(new Avanciro\Skel\Console\Commands\Version);
$Console->add(new Avanciro\Skel\Console\Commands\Update);

// RUN
$Console->run();


?>