#!/usr/bin/env php
<?php
require_once __DIR__."/libs/autoload.php";
$Console = new Symfony\Component\Console\Application;

// COMMANDS
$Console->add(new Avanciro\Skel\Console\Commands\Version);
$Console->add(new Avanciro\Skel\Console\Commands\Update);
$Console->add(new Avanciro\Skel\Console\Commands\Backup\Database);

// DATABASE
$Console->add(new Avanciro\Skel\Console\Commands\Database\Seeder);
$Console->add(new Avanciro\Skel\Console\Commands\Database\Migration);

// RUN
$Console->run();

?>